/*
window.syncOtherPlayerFrameDelay = 0; //30 frames allows for 500ms of network jitter, to prevent late frames
window.currentChannelName; // Global variable for the current channel that your player character is on
window.currentFireChannelName; // Global variable that checks the current stage you are on to send the correct information to the PubNub Block
window.globalCurrentLevel = 0; // Global variable for the current level (index starts at 0)
window.UniqueID = Math.random()*10000000; // Generate a unique id for the player. Generated by the PubNub Network
window.globalLevelState = null; // Sets the globalLevelState to null if you aren't connected to the network. Once connected, the level will generate to the info that was on the block.
window.globalWasHeroMoving = true;
// console.log('UniqueID', UniqueID); // Print out your clientsr Unique ID
window.updateOccupancyCounter = false; // Occupancy Counter variable to check if the timer has already been called in that scene
window.keyMessages = [];


window.createMyPubNub = function (currentLevel) {
  // console.log('createMyPubNub', currentLevel);
  window.globalCurrentLevel = currentLevel; // Get the current level and set it to the global level

  //The channels should be the same while we have only one map/level
  window.currentFireChannelName = 'realtimephaserFire2';
  window.currentChannelName = `realtimephaser${currentLevel}`; // Create the channel name + the current level. This way each level is on its own channel.
  let checkIfJoined = false; // If player has joined the channel
  // Setup your PubNub Keys
  window.pubnub = new window.PubNub({
    publishKey: 'pub-c-341e4eab-1e92-41c2-a707-eeb0a8e97e43',
    subscribeKey: 'sub-c-645faf0a-7143-11ea-8eaf-9ea4064cf66f',
    uuid: window.UniqueID,
  });
  // Subscribe to the two PubNub Channels
  window.pubnub.subscribe({
    channels: [window.currentChannelName, window.currentFireChannelName],
    withPresence: true,
  });
  // ADD LISTENER HERE


  window.sendKeyMessage = (keyMessage) => {
  try {
    if (window.globalMyHero) {
      window.pubnub.publish({
        message: {
          uuid: window.UniqueID,
          keyMessage,
          position: window.globalMyHero.body.position,
          frameCounter: window.frameCounter
        },
        channel: window.currentChannelName,
        sendByPost: false, // true to send via posts
      });
    }
	      // console.log("send message!")
	  } catch (err) {
	    console.log(err);
	  }
	};
	window.fireCoins = () => {
	  const message = {
	    uuid: window.UniqueID,
	    coinCache: window.globalLevelState.coinCache,
	    currentLevel: window.globalCurrentLevel,
	    time: window.globalLastTime
	  };
	  // console.log('fireCoins', message);
	  window.pubnub.fire(
	    {
	      message,
	      channel: window.currentFireChannelName,
	      sendByPost: false, // true to send via posts
	    });
	};

  //MOVE ON

  // If person leaves or refreshes the window, run the unsubscribe function
  window.addEventListener('beforeunload', () => {
    navigator.sendBeacon(`https://pubsub.pubnub.com/v2/presence/sub_key/mySubKey/channel/ch1/leave?uuid=${window.UniqueID}`); // pub
    window.globalUnsubscribe();
  });
  // Unsubscribe people from PubNub network
  window.globalUnsubscribe = function () {
    try {
      // console.log('unsubscribing', window.currentChannelName);
      window.pubnub.unsubscribe({
        channels: [window.currentChannelName, window.currentFireChannelName],
        withPresence: true
      });
      window.pubnub.removeListener(window.listener);
    } catch (err) {
      console.log("Failed to UnSub");
    }
  };
  window.pubnub.addListener(window.listener);
};

*/


window.addEventListener("load", function(event) {
	const AssetsManager = function() {
		this.playerSprite = undefined;
		this.bulletSprite = undefined;
	};

	AssetsManager.prototype = {
		constructor: Game.AssetsManager, requestImage:function(url, callback) {
			let image = new Image();
			image.addEventListener("load", function(event) {
				callback(image);
			}, { once:true });
			image.src = url;
		}
	};

	// var functions
	var keyDownUp = function(event) {
		controller.keyDownUp(event.type, event.keyCode);
	};
	var resize = function(event) {
		display.resize(document.documentElement.clientWidth, document.documentElement.clientHeight, height / width);
		display.render();
	};
	var render = function() {
		display.update(game.world.width,game.world.height);
		// add camera later
		for(let i = 0; i < game.world.me.bullets.length; i++){
			display.drawImg(assets_manager.bulletSprite, game.world.me.bullets[i].x-1,game.world.me.bullets[i].y-20,20, game.world.me.bullets[i].angleInDeg + 180 + 45);
		}
		display.drawImg(assets_manager.playerSprite, game.world.me.x-25,game.world.me.y-25,50, game.world.me.angleInDeg + 90);
		// render gameobjects
		display.render();
	};
	var update = function(t) {
		// something like... 
		if (controller.left.active) {
			game.world.me.control = -1;
		} else if (controller.right.active) {
			game.world.me.control = 1;
		}
		else{
			game.world.me.control = 0;
		}
		game.update(t);
		return;
	};
	setInterval(function(){
		if(needResize == true){
			clearElements();

			needResize = false; 
			resize();
		}
	}, 100);

	var display        = new Display(document.querySelector("canvas"));
	var game           = new Game(1000,600); // pixel resolution (probrably will want it to be low for fps but high for world size + cam.
	var engine         = new Engine(1000/30, render, update);
	var controller     = new Controller();
	var assets_manager = new AssetsManager();


	const width = game.world.width;
	const height = game.world.height;

	display.buffer.canvas.height = height;
	display.buffer.canvas.width  = width;
	display.buffer.imageSmoothingEnabled = false; //  sure??  ************************************************************************************!!!!!!!!!

	game.world.setup();
	
	assets_manager.requestImage("imgs/rocket.png", (image) => {

		assets_manager.playerSprite = image;

		assets_manager.requestImage("imgs/nuke.png", (image) => {

			assets_manager.bulletSprite = image;
			
		});
		
		resize();
		engine.start();

	});


	window.addEventListener("keydown", keyDownUp);
	window.addEventListener("keyup"  , keyDownUp);
	window.addEventListener("resize" , resize);

});


